### ISSUE TITLE
Unable to run latest AppImage on Arch Linux (Antergos)

### ISSUE THREAD

**Issue by scotnewbury** [chrisknepper/android-messages-desktop#18]
I pulled the latest AppImage (0.5) and placed it in /opt/android-messages changed the permissions and attempted to launch the application.

The prompt to integrate the program came up and it did successfully add the icon and then nothing. When I ran it from the terminal I get a module.js:545 error. I've copied the error message below along with the Arch version information.

**Error message**
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_androioJtaYJ/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3

**Version Info**
4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux

**Comment by chrisknepper** [comment]
Thanks for reporting this! I don't have too much experience with desktop Linux unfortunately. I can dig into this when I have some time, but the first thing that strikes me is the path to that module. It probably shouldn't be under `/tmp/`. The `electron.asar` should be in a sub-directory of whatever directory the binary is in.

**Comment by zwickel** [comment]
Same issue here with the AppImage on Arch Linux (Manjaro).

**Comment by ukulanne** [comment]
What I did was pull the gt module and then `npm run release` and then execute android-messages-desktop under dist/linux-unpacked as I am unfamiliar with snap and AppImage. I am running on Fedora 29. The app seems to work find but I cannot get system tray icon / notifications working.

**Comment by scotnewbury** [comment]
AppImage is a way of packaging linux versions of an application so that they can be executed from the command line. You just need to change the permissions on it. Check out [https://appimage.org/](https://appimage.org/)

**Comment by chrisknepper** [comment]
Ah, I'm also unfamiliar with the various Linux packaging systems. I'm wondering if the resulting folder structure that @scotnewbury got from running the AppImage matches the linux-unpacked directory @ukulanne is using.

BTW, as far as tray icon support, I kept that for Windows only because I don't have a Linux distro installed at the moment and didn't want to risk breaking the app for Linux users. If you'd like to test that (which would be a great help!), you could comment out the `if (IS_WINDOWS)` guard around the tray code in `src/background.js` and re-build. You may also want to get rid of the `IS_LINUX` code beneath that as well.

And as far as notification support, I wasn't aware they weren't working on Linux. Electron docs say [they're supported](https://electronjs.org/docs/tutorial/notifications#linux), what's your DE?

**Comment by scotnewbury** [comment]
So I had a couple of minutes, pulled node.js, and cloned the project locally.

When I compile the project I receive the same error for the AppImage (while annoying it does reproduce the issue consistantly). I can however go into the dist/linux-unpacked directory and execute the android-messages-desktop from there, this would lead me to believe that the build for the AppImage is broken.

I should note that I did receive a message that the APPIMAGE env was not defined when I executed the app this way.

When I get a chance I'll take a look at the directory structures and see if anything looks odd.

**Comment by rockmn24** [comment]
I just tested the .deb using [debtap](https://github.com/helixarch/debtap). Works perfectly if anyone is looking for another install option. (tested on LTS kernel 4.9.78)

**Comment by chrisknepper** [comment]
Hey all, 0.4.0 includes a .pacman build binary. Would you Arch users mind testing and seeing if it works the same/better than the .deb?

**Comment by scotnewbury** [comment]
I downloaded the .pacman file and it installed and ran just fine. I was able to sync up my phone and sending and receiving messages seems to be working as well.

**Comment by jacob-swenson** [comment]
The .pacman is running great for me and is definitely preferred over the .deb.

**Comment by zwickel** [comment]
Yes, the .pacman file works great. Just updated with the package from aur :-) great work!
